# Generated by Django 3.0 on 2020-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_doctor_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_hystory',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
