# Generated by Django 3.0 on 2020-12-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_patient_patient_hystory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_hystory',
            new_name='patient_history',
        ),
    ]
